Fix/folders
Kakon24/-OmegaLambda pull request #31
Opened 2020-09-05 18:31 UTC by Michael-Reefe

2020-09-05 18:32 UTC, Michael-Reefe commented
Fixes a minor issue where multiple tickets run at once would save to the same folder

2020-09-08 13:59 UTC, Kakon24 requested changes
Minor changes

2020-09-08 13:59 UTC, Kakon24 commented on main/drivers/driver.py
> +    return sorted(_list, key=alphanum_sorting)
This is great stuff.

2020-09-08 13:59 UTC, Kakon24 commented on main/drivers/driver.py
> +    print('New directories for tonight\'s observing have been made!')
This should be a log?

2020-09-08 13:59 UTC, Kakon24 commented on main/observing/observation_run.py
> +                    print("Still waiting for good conditions to reopen.")
Should be logged?

2020-09-08 13:59 UTC, Kakon24 commented on main/observing/observation_run.py
> +            print("It is not the start time {} of {} observation, "
Logger

2020-09-09 12:25 UTC, Kakon24 approved these changes

2020-09-09 12:25 UTC, merged