Additions to folder saving for the dev branch
Kakon24/-OmegaLambda pull request #32
Opened 2020-09-05 18:32 UTC by Michael-Reefe

2020-09-06 02:46 UTC, Michael-Reefe commented
Identical to #31, but for dev

2020-09-09 12:39 UTC, Kakon24 requested changes
Minor changes

2020-09-09 12:39 UTC, Kakon24 commented on main/observing/calibration.py
> +            print('Dark folder already exists!  Assuming they have been collected, & aborting dark collection...')
Log

2020-09-09 12:39 UTC, Kakon24 commented on main/observing/calibration.py
> +            print('Flat folder already exists!  Assuming they have been collected, & aborting flat collection.')
Log

2020-09-09 14:12 UTC, Kakon24 approved these changes

2020-09-09 14:12 UTC, merged